FROM mcr.microsoft.com/mssql/server:latest
COPY ["TutorPro/DataBaseDockerFile/init/init.sql", "/docker-entrypoint-initdb.d/"]
ENV SA_PASSWORD=YourStrong@Passw0rd
ENV ACCEPT_EULA=Y
ENV MSSQL_BACKUP_DIR="/var/opt/mssql"
ENV MSSQL_DATA_DIR="/var/opt/mssql/data"
ENV MSSQL_LOG_DIR="/var/opt/mssql/log"
EXPOSE 1433
RUN /opt/mssql/bin/sqlservr & sleep 10 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -i docker-entrypoint-initdb.d/init.sql

